### ISSUE TITLE
PDB throws cryptic exceptions when trying to use an inexistent/unreachable database (or any other wrong configurations)

### ISSUE THREAD

**Issue by Pitxyoki** [feedzai/pdb#1]
Hi,

When PDB is configured to use a given database, it is hard to tell if there is a problem on the configuration, a transient network error, or if something is wrong with PDB itself.

You can see the problem by applying the following gist and running the tests included in PDB itself:
https://gist.github.com/anonymous/f96162ecb64f70c82799

You can run only a single test to see the problem:
```
mvn test -e -Dtest=com.feedzai.commons.sql.abstraction.engine.impl.oracle.OracleEngineSchemaTest
(...)

Stacktrace was: com.feedzai.commons.sql.abstraction.engine.DatabaseFactoryException: java.lang.reflect.InvocationTargetException
	at com.feedzai.commons.sql.abstraction.engine.DatabaseFactory.getConnection(DatabaseFactory.java:89)
	at com.feedzai.commons.sql.abstraction.engine.impl.abs.EngineCreateTest.stopsWhenTableAlreadyExistsTest(EngineCreateTest.java:165)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:158)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:86)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at com.feedzai.commons.sql.abstraction.engine.DatabaseFactory.getConnection(DatabaseFactory.java:64)
	... 13 more
Caused by: com.feedzai.commons.sql.abstraction.engine.DatabaseEngineException: Unable to connect to database
	at com.feedzai.commons.sql.abstraction.engine.AbstractDatabaseEngine.<init>(AbstractDatabaseEngine.java:158)
	at com.feedzai.commons.sql.abstraction.engine.impl.OracleEngine.<init>(OracleEngine.java:83)
	... 16 more
Caused by: java.sql.SQLRecoverableException: IO Error: The Network Adapter could not establish the connection
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:489)
	at oracle.jdbc.driver.PhysicalConnection.<init>(PhysicalConnection.java:553)
	at oracle.jdbc.driver.T4CConnection.<init>(T4CConnection.java:254)
	at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:32)
	at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:528)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at com.feedzai.commons.sql.abstraction.engine.AbstractDatabaseEngine.connect(AbstractDatabaseEngine.java:217)
	at com.feedzai.commons.sql.abstraction.engine.AbstractDatabaseEngine.<init>(AbstractDatabaseEngine.java:154)
	... 17 more
Caused by: oracle.net.ns.NetException: The Network Adapter could not establish the connection
	at oracle.net.nt.ConnStrategy.execute(ConnStrategy.java:439)
	at oracle.net.resolver.AddrResolution.resolveAndExecute(AddrResolution.java:454)
	at oracle.net.ns.NSProtocol.establishConnection(NSProtocol.java:693)
	at oracle.net.ns.NSProtocol.connect(NSProtocol.java:251)
	at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1140)
	at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:340)
	... 25 more
Caused by: java.net.UnknownHostException: inexistent_host
	at java.net.InetAddress.getAllByName0(InetAddress.java:1259)
	at java.net.InetAddress.getAllByName(InetAddress.java:1171)
	at java.net.InetAddress.getAllByName(InetAddress.java:1105)
	at oracle.net.nt.TcpNTAdapter.connect(TcpNTAdapter.java:117)
	at oracle.net.nt.ConnOption.connect(ConnOption.java:133)
	at oracle.net.nt.ConnStrategy.execute(ConnStrategy.java:405)
	... 30 more

(...)
```

The problem I have with this is that the `DatabaseFactory.getConnection(Properties)` method is throwing an `InvocationTargetException` when a simple mistake like a wrong hostname or IP address was given on the database configuration.
`InvocationTargetException` is an unchecked exception, and is not even declared on getConnection's signature. The cause for this Exception is only detectable by looking at the exception and iteratively navigating through the `cause()`s of this exception.
This makes it very hard to debug, and it is a situation that should be easy to handle by the API user, so that a cleaner resolution for configuration problems like these can be provided to the end-user.
Other, equally cryptic exceptions, can be thrown in the case of other configuration errors.

I propose a more reasonable behaviour should be provided instead. Configuration problems should be detected and explicit, obvious exceptions should be thrown for those cases.

For example, declare that a *checked* `UnableToConnectException` or even an `IncorrectConfigurationException` can be thrown by `getConnection()` (or a new version of it to avoid breaking the current API). Alternatively, a `validateConfigurations` method can be provided to be called before trying to establish the connection.

Note: I have only tested this with Oracle, and with the given error. Other configuration errors may throw other kinds of hard-to-debug (or easier?) exceptions that should also be treated more elegantly, but I didn't check that thoroughly.

Thanks.

**Comment by HiuKwok** [comment]
Yes, I do agree the current PDB design especially on `DatabaseFactory` which make API user hard to debug when they configured DB properties wrongly. However I'm kind of opposite the idea of  adding extra exception class to address this.

There is not much value of catching those exception, let consider the case of database user password mismatch and we have an associated exception, but there is not much action to perform in order to fix this within the catch `clause`.

In the case of password mismatch, the logical follow up will be going back to check the configuration file and restart application to make it effective and on this case you probably realize the system is not starting up correctly and start to investigate against PDB log.
