### ISSUE TITLE
Not sure what happens when the database connection goes down, or if it will ever stop

### ISSUE THREAD

**Issue by Pitxyoki** [feedzai/pdb#2]
When a database connection goes down, it is not clear what is PDB going to do.

The messages printed on the console show that connection retries are being performed, but it seems that they will never end, although the displayed counter seems to imply so.

Although I'm not sure if this is needed (and whether you can reproduce it with H2), you can use docker to reproduce the issue on Oracle more easily:
```
$ docker pull filemon/oracle_11g
$ docker run -d --name oracle -p 1521:1521 filemon/oracle_11g
```
An Oracle database will be running on your local machine.

Then apply  the following gist: https://gist.github.com/anonymous/794bac8bd2d8fdf15a2b
And then run the relevant test: 
```
$ mvn  clean test -Dtest=com.feedzai.commons.sql.abstraction.engine.impl.oracle.OracleEngineSchemaTest
```

You should see the following output:
```
(...)
11:15:34.995 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection successful.
Test waiting for 10 seconds...
Test waiting for 10 seconds...
Test waiting for 10 seconds...
```

Now kill the Oracle database to make the connection go down:
```
$ docker rm -f oracle
oracle
$
```

The following will be seen on the console. It is not clear if this will ever end, and if so, what should be the correct action to be taken by the API user:
```
Test waiting for 10 seconds...
11:16:05.352 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection is down.
java.sql.SQLRecoverableException: No more data to read from socket
	at oracle.jdbc.driver.T4CMAREngine.unmarshalUB1(T4CMAREngine.java:1157) ~[ojdbc6-11.2.0.2.0.jar:11.2.0.4.0]
	at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:350) ~[ojdbc6-11.2.0.2.0.jar:11.2.0.4.0]
	at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:227) ~[ojdbc6-11.2.0.2.0.jar:11.2.0.4.0]
	at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:531) ~[ojdbc6-11.2.0.2.0.jar:11.2.0.4.0]
	at oracle.jdbc.driver.T4CStatement.doOall8(T4CStatement.java:195) ~[ojdbc6-11.2.0.2.0.jar:11.2.0.4.0]
	at oracle.jdbc.driver.T4CStatement.executeForDescribe(T4CStatement.java:876) ~[ojdbc6-11.2.0.2.0.jar:11.2.0.4.0]
	at oracle.jdbc.driver.OracleStatement.executeMaybeDescribe(OracleStatement.java:1175) ~[ojdbc6-11.2.0.2.0.jar:11.2.0.4.0]
	at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1296) ~[ojdbc6-11.2.0.2.0.jar:11.2.0.4.0]
	at oracle.jdbc.driver.OracleStatement.executeQuery(OracleStatement.java:1498) ~[ojdbc6-11.2.0.2.0.jar:11.2.0.4.0]
	at oracle.jdbc.driver.OracleStatementWrapper.executeQuery(OracleStatementWrapper.java:406) ~[ojdbc6-11.2.0.2.0.jar:11.2.0.4.0]
	at com.feedzai.commons.sql.abstraction.engine.impl.OracleEngine.checkConnection(OracleEngine.java:782) ~[classes/:na]
	at com.feedzai.commons.sql.abstraction.engine.AbstractDatabaseEngine.getConnection(AbstractDatabaseEngine.java:272) [classes/:na]
	at com.feedzai.commons.sql.abstraction.engine.AbstractDatabaseEngine.beginTransaction(AbstractDatabaseEngine.java:408) [classes/:na]
	at com.feedzai.commons.sql.abstraction.engine.impl.oracle.OracleEngineSchemaTest.waitForever(OracleEngineSchemaTest.java:71) [test-classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_11]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_11]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_11]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_11]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47) [junit-4.11.jar:na]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.11.jar:na]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44) [junit-4.11.jar:na]
	at mockit.integration.junit4.internal.JUnit4TestRunnerDecorator.executeTestMethod(JUnit4TestRunnerDecorator.java:141) [jmockit-1.9.jar:na]
	at mockit.integration.junit4.internal.JUnit4TestRunnerDecorator.invokeExplosively(JUnit4TestRunnerDecorator.java:71) [jmockit-1.9.jar:na]
	at mockit.integration.junit4.internal.MockFrameworkMethod.invokeExplosively(MockFrameworkMethod.java:44) [jmockit-1.9.jar:na]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java) [junit-4.11.jar:na]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.11.jar:na]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) [junit-4.11.jar:na]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271) [junit-4.11.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70) [junit-4.11.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50) [junit-4.11.jar:na]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238) [junit-4.11.jar:na]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63) [junit-4.11.jar:na]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236) [junit-4.11.jar:na]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53) [junit-4.11.jar:na]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229) [junit-4.11.jar:na]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309) [junit-4.11.jar:na]
	at org.junit.runners.Suite.runChild(Suite.java:127) [junit-4.11.jar:na]
	at org.junit.runners.Suite.runChild(Suite.java:26) [junit-4.11.jar:na]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238) [junit-4.11.jar:na]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63) [junit-4.11.jar:na]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236) [junit-4.11.jar:na]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53) [junit-4.11.jar:na]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229) [junit-4.11.jar:na]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309) [junit-4.11.jar:na]
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264) [surefire-junit4-2.14.jar:2.14]
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153) [surefire-junit4-2.14.jar:2.14]
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124) [surefire-junit4-2.14.jar:2.14]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_11]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_11]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_11]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_11]
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:208) [surefire-api-2.14.jar:2.14]
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:158) [surefire-booter-2.14.jar:2.14]
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:86) [surefire-booter-2.14.jar:2.14]
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153) [surefire-booter-2.14.jar:2.14]
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:95) [surefire-booter-2.14.jar:2.14]
11:16:05.355 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection is down.
11:16:05.355 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 1 in 10 seconds...
11:16:15.362 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:16:15.363 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 2 in 10 seconds...
11:16:25.366 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:16:25.367 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 3 in 10 seconds...
11:16:35.372 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:16:35.374 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 4 in 10 seconds...
11:16:45.379 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:16:45.380 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 5 in 10 seconds...
11:16:55.384 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:16:55.384 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 6 in 10 seconds...
11:17:05.387 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:17:05.387 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 7 in 10 seconds...
11:17:15.391 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:17:15.391 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 8 in 10 seconds...
11:17:25.394 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:17:25.394 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 9 in 10 seconds...
11:17:35.397 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:17:35.398 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 10 in 10 seconds...
11:17:35.398 [main] ERROR admin-notifications - The connection to the database was lost. Retry number 10 in 10
11:17:45.405 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:17:45.406 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 11 in 10 seconds...
11:17:55.409 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:17:55.411 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 12 in 10 seconds...
11:18:05.413 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:18:05.413 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 13 in 10 seconds...
11:18:15.416 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:18:15.417 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 14 in 10 seconds...
11:18:25.420 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:18:25.421 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 15 in 10 seconds...
11:18:35.424 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:18:35.425 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 16 in 10 seconds...
11:18:45.429 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:18:45.429 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 17 in 10 seconds...
11:18:55.431 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:18:55.431 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 18 in 10 seconds...
11:19:05.433 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:19:05.433 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 19 in 10 seconds...
11:19:15.438 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:19:15.441 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 20 in 10 seconds...
11:19:15.442 [main] ERROR admin-notifications - The connection to the database was lost. Retry number 20 in 10
11:19:25.446 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:19:25.446 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 21 in 10 seconds...
11:19:35.450 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:19:35.451 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 22 in 10 seconds...
11:19:45.457 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:19:45.457 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 23 in 10 seconds...
11:19:55.465 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:19:55.466 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 24 in 10 seconds...
11:20:05.469 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:20:05.471 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 25 in 10 seconds...
11:20:15.474 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:20:15.474 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 26 in 10 seconds...
11:20:25.476 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:20:25.476 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 27 in 10 seconds...
11:20:35.478 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:20:35.479 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 28 in 10 seconds...
11:20:45.485 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:20:45.485 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 29 in 10 seconds...
11:20:55.488 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:20:55.488 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 30 in 10 seconds...
11:20:55.488 [main] ERROR admin-notifications - The connection to the database was lost. Retry number 30 in 10
11:21:05.490 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:21:05.491 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 31 in 10 seconds...
11:21:15.492 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:21:15.493 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 32 in 10 seconds...
11:21:25.494 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:21:25.495 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 33 in 10 seconds...
11:21:35.497 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:21:35.498 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 34 in 10 seconds...
11:21:45.500 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:21:45.501 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 35 in 10 seconds...
11:21:55.504 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:21:55.504 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 36 in 10 seconds...
11:22:05.507 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:22:05.509 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 37 in 10 seconds...
11:22:15.517 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:22:15.517 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 38 in 10 seconds...
11:22:25.520 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:22:25.520 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 39 in 10 seconds...
11:22:35.529 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:22:35.529 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 40 in 10 seconds...
11:22:35.529 [main] ERROR admin-notifications - The connection to the database was lost. Retry number 40 in 10
11:22:45.532 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:22:45.532 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 41 in 10 seconds...
11:22:55.535 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:22:55.536 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 42 in 10 seconds...
11:23:05.542 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:23:05.543 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 43 in 10 seconds...
11:23:15.547 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:23:15.548 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 44 in 10 seconds...
11:23:25.551 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:23:25.552 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 45 in 10 seconds...
11:23:35.555 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:23:35.556 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 46 in 10 seconds...
11:23:45.558 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:23:45.559 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 47 in 10 seconds...
11:23:55.562 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:23:55.563 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 48 in 10 seconds...
11:24:05.565 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:24:05.565 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 49 in 10 seconds...
11:24:15.568 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:24:15.568 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 50 in 10 seconds...
11:24:15.568 [main] ERROR admin-notifications - The connection to the database was lost. Retry number 50 in 10
11:24:25.574 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:24:25.574 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 51 in 10 seconds...
11:24:35.576 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:24:35.576 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 52 in 10 seconds...
11:24:45.579 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:24:45.579 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 53 in 10 seconds...
11:24:55.582 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:24:55.583 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 54 in 10 seconds...
11:25:05.585 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:25:05.586 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 55 in 10 seconds...
11:25:15.589 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:25:15.591 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 56 in 10 seconds...
11:25:25.594 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:25:25.594 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 57 in 10 seconds...
11:25:35.598 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:25:35.599 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 58 in 10 seconds...
11:25:45.602 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:25:45.605 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 59 in 10 seconds...
11:25:55.608 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:25:55.612 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 60 in 10 seconds...
11:25:55.612 [main] ERROR admin-notifications - The connection to the database was lost. Retry number 60 in 10
11:26:05.616 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:26:05.617 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 61 in 10 seconds...
11:26:15.621 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:26:15.621 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 62 in 10 seconds...
11:26:25.624 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:26:25.624 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 63 in 10 seconds...
11:26:35.626 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:26:35.626 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 64 in 10 seconds...
11:26:45.632 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:26:45.632 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 65 in 10 seconds...
11:26:55.635 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:26:55.635 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 66 in 10 seconds...
11:27:05.640 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:27:05.642 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 67 in 10 seconds...
11:27:15.644 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:27:15.645 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 68 in 10 seconds...
11:27:25.658 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:27:25.658 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 69 in 10 seconds...
11:27:35.660 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:27:35.661 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 70 in 10 seconds...
11:27:35.661 [main] ERROR admin-notifications - The connection to the database was lost. Retry number 70 in 10
11:27:45.663 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:27:45.663 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 71 in 10 seconds...
11:27:55.665 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:27:55.665 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 72 in 10 seconds...
11:28:05.666 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Connection failed.
11:28:05.666 [main] DEBUG c.f.c.s.a.engine.impl.OracleEngine - Retry number 73 in 10 seconds...
(...)
```

**Comment by HiuKwok** [comment]
Yes, the `MAX_NUMBER_OF_RETRIES` and `RETRY_INTERVAL` are configurable, see:
https://github.com/feedzai/pdb/blob/e7364e267518182ecab5da9e6fdc5659fee630f8/src/main/java/com/feedzai/commons/sql/abstraction/engine/configuration/PdbProperties.java#L195

When PDB encounter connection failure, it will attempt to reconnect according to the configuration set above.
https://github.com/feedzai/pdb/blob/e7364e267518182ecab5da9e6fdc5659fee630f8/src/main/java/com/feedzai/commons/sql/abstraction/engine/AbstractDatabaseEngine.java#L345

` RetryLimitExceededException` will be thrown if connection still can't be established after exhausted all retries and this will be wrapped by either `DatabaseEngineRuntimeException` or `DatabaseEngineException` depends on the API call that you made. 

https://github.com/feedzai/pdb/blob/e7364e267518182ecab5da9e6fdc5659fee630f8/src/main/java/com/feedzai/commons/sql/abstraction/engine/AbstractDatabaseEngine.java#L515

https://github.com/feedzai/pdb/blob/e7364e267518182ecab5da9e6fdc5659fee630f8/src/main/java/com/feedzai/commons/sql/abstraction/engine/AbstractDatabaseEngine.java#L539
